# --- !Ups

create table "errors" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "date" varchar not null
);

# --- !Downs

drop table "errors" if exists;
